name: "LazyPR"
description: "Generates AI-powered PR summaries with Ghost Commit detection, impact scoring, and automated reviewer checklists"
author: "elvis-ndubuisi"
homepage: "https://github.com/elvis-ndubuisi/lazypr"
repository: "https://github.com/elvis-ndubuisi/lazypr"

inputs:
  api_key:
    description: "API key for your LLM provider (OpenAI, Anthropic, or Google Gemini)"
    required: true
  provider:
    description: "LLM provider to use (openai, anthropic, or gemini)"
    required: false
    default: "openai"
  model:
    description: "Model to use (defaults to provider-specific model if not specified)"
    required: false
    default: ""
  template:
    description: "Prompt template to use (default, concise, verbose, security-focused)"
    required: false
    default: "default"
  github_token:
    description: "GitHub token for API access (automatically provided by GitHub Actions)"
    required: false
    default: ${{ github.token }}

outputs:
  summary:
    description: "Generated PR summary"
  has_ghost_commits:
    description: "Whether ghost commits were detected"
  risk_level:
    description: "Risk level of the PR changes (LOW, MEDIUM, or HIGH)"
  impact_score:
    description: "Impact score from 0-100"

runs:
  using: "node20"
  main: "dist/index.js"

branding:
  icon: "git-pull-request"
  color: "purple"
