export interface PromptTemplate {
  name: string;
  description: string;
  template: string;
  systemPrompt?: string;
}

const TEMPLATES: Record<string, PromptTemplate> = {
  securityFocused: {
    name: "Security Focused",
    description: "Emphasize security implications, auth changes, and potential vulnerabilities",
    template: `## Security Analysis

Analyze this pull request with a focus on security concerns:

### Files Changed
{{filesChanged}}

### Diff
{{diff}}

### Risk Assessment
Classify the risk level as **LOW**, **MEDIUM**, or **HIGH** based on:
- Changes to authentication/authorization logic
- Database/schema modifications
- API endpoint changes
- Sensitive data handling
- Dependency updates

### Security Concerns
List any potential security issues found:
- [ ] Authentication bypass risks
- [ ] Authorization/permission issues
- [ ] Input validation problems
- [ ] SQL injection risks
- [ ] XSS/CSRF vulnerabilities
- [ ] Secrets exposure
- [ ] Dependency vulnerabilities

### Reviewer Checklist
- [ ] Verify auth logic changes
- [ ] Check for hardcoded credentials
- [ ] Validate input sanitization
- [ ] Review database migrations`,
  },
  concise: {
    name: "Concise",
    description: "Brief summary only",
    template: `## PR Summary

**TL;DR:** {{prTitle}}

### Key Changes
- {{summary}}

### Risk Level: {{riskLevel}}`,
    systemPrompt:
      "You are a helpful assistant that summarizes pull requests concisely. Keep your response brief and focused on the most important changes.",
  },
  verbose: {
    name: "Verbose",
    description: "Detailed analysis with file breakdown",
    template: `## Detailed PR Analysis

### Pull Request Information
- **Title:** {{prTitle}}
- **Author:** {{prAuthor}}
- **Files Changed:** {{filesChanged}}
- **Commits:** {{commitCount}}

### Summary
{{prBody}}

### Files Breakdown
{{fileBreakdown}}

### Code Changes Analysis
{{detailedAnalysis}}

### Risk Assessment: {{riskLevel}}

### Impact Areas
- **Breaking Changes:** {{breakingChanges}}
- **Deprecations:** {{deprecations}}
- **New Dependencies:** {{newDeps}}
- **Removed Features:** {{removedFeatures}}

### Reviewer Checklist
- [ ] Code quality review
- [ ] Test coverage verification
- [ ] Documentation updates
- [ ] Security review (if applicable)
- [ ] Performance impact assessment

### Notes for Reviewers
{{additionalNotes}}`,
  },
  default: {
    name: "Default",
    description: "Standard PR summary template",
    template: `## 🚀 PR Summary: {{prTitle}}

### TL;DR
{{tlDr}}

### 🛠 Key Changes
{{keyChanges}}

### 📊 Risk Assessment: {{riskLevel}}

### 🕵️ Reviewer Checklist
{{reviewerChecklist}}

---
*Generated by lazypr*`,
  },
};

export const templates: Record<string, PromptTemplate> = TEMPLATES;

export function getTemplate(name: string): PromptTemplate {
  const resolvedName = resolveTemplateName(name);
  const key = resolvedName as keyof typeof TEMPLATES;
  if (key in TEMPLATES) {
    const result = TEMPLATES[key];
    return result as PromptTemplate;
  }
  return TEMPLATES.default as PromptTemplate;
}

export function getAllTemplates(): PromptTemplate[] {
  return Object.values(TEMPLATES);
}

export function templateExists(name: string): boolean {
  const resolvedName = resolveTemplateName(name);
  const key = resolvedName as keyof typeof TEMPLATES;
  return key in TEMPLATES;
}

export function resolveTemplateName(input: string): string {
  const normalized = input.toLowerCase().replace(/[-_\s]/g, "");
  const mapping: Record<string, keyof typeof TEMPLATES> = {
    security: "securityFocused",
    securityfocused: "securityFocused",
    concise: "concise",
    brief: "concise",
    short: "concise",
    simple: "concise",
    verbose: "verbose",
    detailed: "verbose",
    detailedanalysis: "verbose",
    full: "verbose",
    standard: "default",
  };
  return mapping[normalized] ?? "default";
}
